---
- name: Prepare env on localhost
  hosts: localhost
  vars_files: vault.yml
  roles:
    - role: pip_requierements
    - role: clone-template
      ignore_errors: yes

- name: set hostname
  hosts: spawned
  vars_files: vault.yml
  roles:
    - role: set-hostname
      become: true
