---
- name: Prepare env on localhost
  hosts: localhost
  roles:
    - role: pip_requierements
    - role: clone-template
      ignore_errors: yes

- hosts: spawned
  roles:
    - role: set-hostname
      become: true
