- name: Change Network
  hosts: all
  vars_files: vault.yml
  roles:
    - role: ipconfig
      become: true

- name: switch bridge
  hosts: localhost
  vars_files: vault.yml
  roles:
    - role: switch-bridge

