---
- name: Install ad packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ad_packages }}"

- name:  Add /etc/krb5.conf
  ansible.builtin.template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
