---
- name: Get network brides
  ansible.builtin.shell: echo $(cat /etc/network/interfaces | grep "auto vmbr*" | sed "s/auto /\"/g") | sed "s/ /\", /g" | sed "s/$/\"/"
  register: bridges

- name: Get Templates
  ansible.builtin.shell: echo $(pvesh get /cluster/resources --type vm --output-format yaml | grep name | grep -i template | sed "s/^.*name. /\"/g")| sed "s/ /\", /g" | sed 's/$/"/' 
  register: templates
  become: true

- name: Get Ressource Pools
  ansible.builtin.shell: echo $(pvesh ls /pools --output-format yaml | grep name | sed "s/^.*name. /\"/g")| sed "s/ /\", /g" | sed 's/$/"/' 
  register: pools
  become: true

- set_fact: 
    templates={{ templates.stdout }}
    pools={{ pools.stdout }}
    bridges={{ bridges.stdout }}

- name: template
  ansible.builtin.template:
    src: my_survey.json.j2 
    dest: /tmp/out.json
  delegate_to: 127.0.0.1

- name: template
  ansible.builtin.template:
    src: config.j2 
    dest: /tmp/config
  delegate_to: 127.0.0.1


- name: cat
  ansible.builtin.shell: cat /tmp/out.json
  delegate_to: 127.0.0.1

- name: Edit template survey
  awx.awx.job_template:
    controller_config_file: /tmp/config
    validate_certs: false
    name: "{{ survey_template_name }}"
    survey_spec: "{{ lookup('file', '/tmp/out.json') }}"
  delegate_to: 127.0.0.1
