- name: Install gnome  (state=present is optional)                                                                                                         
  ansible.builtin.apt:                                                                                                                                     
    name: task-gnome-desktop                                                                                                                               
    state: present
                                                                                                                                         
- name: Update all packages to their latest version                                                                                                        
  ansible.builtin.apt:                                                                                                                                     
    name: "*"  
    state: latest

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

